config/routes.rb
Rails.application.routes.draw do
  mount DceLti::Engine => "/lti"

  resources :videos, only: [:index, :new, :create, :destroy, :update]

  resource :video, only: [] do
    member do
      get 'my', action: :show
    end
  end

  resource :course, only: [] do
    member do
      get :edit
      patch :update
    end
  end

  root to: 'videos#index'
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :videos,
    dependent: :destroy
  has_many :course_roles,
    dependent: :destroy
  has_many :dce_lti_users,
    through: :course_roles, class_name: DceLti::User

  validates :resource_link_id,
    length: { maximum: 255 },
    presence: true

  validates :title,
    length: { maximum: 255 }

  validates :upload_description, :welcome_message,
    length: { maximum: 2.kilobytes }

  def user_has_role?(user, role)
    self.course_roles.where(dce_lti_user_id: user.id, role: role.downcase).present?
  end

  def grant_roles_for_user(user, roles)
    ActiveRecord::Base.transaction do
      self.course_roles.where(dce_lti_user_id: user.id).destroy_all
      roles.each do |role|
        CourseRole.create!(
          dce_lti_user_id: user.id,
          course_id: self.id,
          role: role
        )
      end
    end
  end
end

app/models/course_role.rb
class CourseRole < ActiveRecord::Base
  belongs_to :dce_lti_user,
    class_name: DceLti::User
  belongs_to :course

  validates :dce_lti_user_id,
    presence: true
  validates :course_id,
    presence: true
  validates :role,
    presence: true
end

app/models/video.rb
class Video < ActiveRecord::Base
  SOURCES = {
    I18n.t('videos.sources.existing') => 'existing',
    I18n.t('videos.sources.no_video') => 'no_video',
  }

  attr_writer :existing_youtube_video

  before_create :ensure_review_is_required

  belongs_to :dce_lti_user, class_name: DceLti::User
  belongs_to :course

  validates :dce_lti_user_id,
    presence: true,
    uniqueness: { scope: :course_id }

  validates :youtube_id,
    length: { maximum: 20 }

  validates :course_id,
    presence: true

  validates :description,
    length: { maximum: 2.kilobytes }

  delegate :review_required?, to: :course

  def existing_youtube_video
    if youtube_id.present? && source == 'existing'
      %Q|https://www.youtube.com/watch?v=#{youtube_id}|
    end
  end

  def self.approved
    where(approved: true)
  end

  def self.not_approved
    where(approved: false)
  end

  def self.by_course_id(course_id)
    where(course_id: course_id)
  end

  private

  def ensure_review_is_required
    if self.course.review_required
      self.approved = false
    else
      self.approved = true
    end
    true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_via_lti
  helper_method :current_user, :course

  private

  def initialize_course
    @course = Course.find_or_initialize_by(
      resource_link_id: session[:resource_link_id]
    )
    if @course.new_record?
      @course.title = session[:context_title]
      @course.save!
    end
  end

  def initialize_course_roles
    course.grant_roles_for_user(current_user, get_roles_from_session)
  end

  def get_roles_from_session
    session[:roles] || []
  end

  def course
    @course
  end

  def only_instructors
    if ! course.user_has_role?(current_user, 'instructor')
      redirect_to root_path
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_filter :initialize_course, :initialize_course_roles, :only_instructors

  def edit
  end

  def update
    begin
      course.review_required = course_params[:review_required]
      course.welcome_message = course_params[:welcome_message]
      course.upload_description = course_params[:upload_description]
      course.save!

      flash[:notice] = t('courses.updated')
      redirect_to edit_course_path
    rescue => e
      flash[:error] = t('courses.save_failed')
      render :edit
    end
  end

  private

  def course_params
    params.fetch(:course, {})
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_filter :initialize_course, :initialize_course_roles
  before_filter :find_my_video, only: [:index, :new]
  before_filter :only_instructors, only: [:update]

  def new
    @video = Video.new
    if @my_video
      @video.description = @my_video.description
      @video.source = @my_video.source
      @video.youtube_id = @my_video.youtube_id
    end
  end

  def show
    @my_video = video_for_current_user || Video.new
  end

  def index
    @filter_set = create_filter_set

    @videos = @filter_set.apply_to(course.videos)
    if ! all_videos_visible?
      @videos = @videos.approved.all
    end
    if @videos.empty?
      flash[:notice] = t("videos.#{course.review_required? ? 'review_required_but_' : 'review_not_required_but_' }none_yet")
    end
  end

  def create
    CourseUserVideoCreator.create(
      youtube_id: video_params[:youtube_id],
      description: video_params[:description],
      source: video_params[:source],
      dce_lti_user_id: current_user.id,
      course_id: course.id
    )
    flash[:notice] = t('videos.updated')
    redirect_to my_video_path
  rescue => e
    logger.warn "Creating a video failed: #{e.inspect}"
    @video = Video.new(video_params)
    render :new
  end

  def destroy
    video = course.videos.find(params[:id])
    if video_can_be_destroyed_by_user?(video)
      video.destroy
      flash[:notice] = t('videos.destroyed')
    end
  rescue => e
    logger.warn "Could not destroy video: #{e.inspect}"
  ensure
    redirect_to root_path
  end

  def update
    begin
      video = course.videos.find(params[:id])
      video.approved = video_params[:approved]
      video.save!
      flash[:notice] = t('videos.updated')
    rescue => e
      flash[:error] = t('videos.save_failed')
      logger.warn "Could not update video: #{e.inspect}"
    ensure
      redirect_to root_path
    end
  end

  private

  def video_can_be_destroyed_by_user?(video)
    course.user_has_role?(current_user,'instructor') ||
      video.dce_lti_user == current_user
  end

  def all_videos_visible?
    ! course.review_required? || course.user_has_role?(current_user,'instructor')
  end

  def video_for_current_user
    Video.by_course_id(course.id).find_by(
      dce_lti_user_id: current_user.id
    )
  end

  def find_my_video
    @my_video = video_for_current_user
  end

  def video_params
    params.require(:video).permit(:description, :youtube_id, :source, :existing_youtube_video, :approved)
  end

  def create_filter_set
    FilterSet.new(params.fetch(:filter_set, {}))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown_format(text)
    if text.present?
      renderer = Redcarpet::Render::HTML.new(
        safe_links_only: true,
        no_styles: true,
        escape_html: true
      )
      markdown = Redcarpet::Markdown.new(
        renderer,
        autolink: true
      )
      %Q|<div class="contextual-message">#{markdown.render(text)}</div>|
    end
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_IO_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.io/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_IO_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div id="flash">
    <% flash.each do |key, value| -%>
      <div class="flash-container flash-<%= key %>"><%= value %><div class="close" style="background-image: url('<%= asset_path('close.png') %>');"></div></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/application/_toolbar.html.erb
<!-- h/t refills.bourbon.io -->
<header class="centered-navigation" role="banner">
  <div class="centered-navigation-wrapper">
    <a href="javascript:void(0)" class="mobile-logo js-centered-navigation-mobile-menu-toggle">
      <img src="<%= image_path('hamburger_menu.png') %>" alt="Logo image">
    </a>
    <a href="javascript:void(0)" id="js-centered-navigation-mobile-menu" class="centered-navigation-mobile-menu js-centered-navigation-mobile-menu-toggle">MENU</a>
    <nav role="navigation">
      <ul id="js-centered-navigation-menu" class="centered-navigation-menu show">
        <% if current_user && course.user_has_role?(current_user, 'instructor') %>
          <li class="nav-link">
            <%= link_to(t('courses.settings'), edit_course_path) %>
          </li>
        <% end %>
        <li class="nav-link">
          <%= link_to(t('titles.homepage'), root_path) %>
        </li>
        <li class="nav-link">
          <%= link_to(t('videos.view_my_video'), my_video_path) %>
        </li>
        <li class="nav-link">
          <%= link_to(t('videos.new'), new_video_path) %>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/courses/edit.html.erb
<div class="full-width">
  <div class="edit-form">
    <h2><%= title %></h2>
    <%= simple_form_for(course) do |f| %>
      <%= f.input :welcome_message, as: :text %>
      <%= f.input :upload_description, as: :text %>
      <%= f.input :review_required %>
      <%= f.button :submit %>
    <% end %>
  </div>
  <div class="preview">
    <h2><%= t('courses.preview') %></h2>
    <div id="welcome-message">
      <h3><%= t('courses.welcome_message') %></h3>
      <%= raw markdown_format(course.welcome_message) %>
    </div>
    <div id="upload-description-message">
      <h3><%= t('courses.upload_description') %></h3>
      <%= raw markdown_format(course.upload_description) %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="ROBOTS" content="NOODP" />
    <meta name="viewport" content="initial-scale=1" />
    <title><%= title %></title>
    <%= stylesheet_link_tag :application, media: "all" %>
    <%= csrf_meta_tags %>
  </head>
  <body class="<%= body_class %>">
    <% if current_user %>
      <%= render "toolbar" -%>
      <%= render "flashes" -%>
    <% end %>
    <div id="body-wrapper">
      <%= yield %>
    </div>
    <%= render "javascript" %>
  </body>
</html>

app/views/refills/_modal.html.erb
<div class="modal">
  <label for="modal-1">
    <div class="modal-trigger">Click for Modal</div>
  </label>
  <input class="modal-state" id="modal-1" type="checkbox" />
  <div class="modal-window">
    <div class="modal-inner">
      <label class="modal-close" for="modal-1"></label>
      <h1>Modal Title</h1>
      <p class="modal-intro">Intro text lorem ipsum dolor sit ametm, quas, eaque facilis aliquid cupiditate tempora cumque ipsum accusantium illo modi commodi  minima.</p>
      <p class="modal-content">Body text lorem ipsum dolor ipsum dolor sit sit possimus amet, consectetur adipisicing elit. Itaque, placeat, explicabo, veniam quos aperiam molestias eriam molestias molestiae suscipit ipsum enim quasi sit possimus quod atque nobis voluptas earum odit accusamus quibusdam. Body text lorem ipsum dolor ipsum dolor sit sit possimus amet.</p>
    </div>
  </div>
</div>

app/views/videos/_dropdown.html.erb
<div class="dropdown">
  <div class="dropdown-container">
    <p class="dropdown-button"><%= image_tag('gear.png', class: 'edit_video_menu') %></p>
    <ul class="dropdown-menu dropdown-select">
      <li><%= link_to(t('videos.destroy'), video_path(video), method: :delete, data: { confirm: t('videos.confirm_destroy') }) %></li>
      <% if video.review_required? && course.user_has_role?(current_user, 'instructor') %>
        <% if video.approved? %>
          <li><%= link_to(t('videos.disapprove'), video_path(video, video: { approved: false }), method: :put) %></li>
        <% else %>
          <li><%= link_to(t('videos.approve'), video_path(video, video: { approved: true }), method: :put) %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/videos/_filters.html.erb
<div id="filters">
  <h2><%= t('videos.filter_by') %></h2>
  <%= simple_form_for(@filter_set, url: videos_path, method: :get) do |f| %>
    <% if course.review_required? && course.user_has_role?(current_user, 'instructor') %>
      <span class="filter_element">
        <%= f.label :approval_state %>
        <%= f.input_field :approval_state, collection: FilterSet.approval_options, default: nil %>
      </span>
    <% end %>
    <span class="filter_element">
      <%= f.label :name %>
      <%= f.input_field :name %>
    </span>
    <span class="filter_element">
      <%= f.label :sort_by %>
      <%= f.input_field :sort_by, collection: FilterSet.sort_by_values, default: nil %>
    </span>
    <%= f.submit %>
  <% end %>
</div>

app/views/videos/_modal_content.html.erb
<div class="modal-inner">
  <label class="modal-close" for="modal-<%= video.id %>"></label>
  <% if video.youtube_id? %>
    <div
      class="youtube_modal_container"
      id="youtube_modal_container_<%= video.id %>"
      data-video-container="<%= dom_id(video) %>"
      data-youtube-id="<%= video.youtube_id %>"
      style="background-image: url('//img.youtube.com/vi/<%= video.youtube_id %>/hqdefault.jpg')"
      >
      <%= image_tag('play_button.png', class: 'play_button') %>
    </div>
  <% end %>
  <% if video.description? %>
    <div class="description">
      <%= raw markdown_format(video.description) %>
    </div>
  <% end %>
  <div class="metadata">
    <%= video.dce_lti_user.lis_person_name_full %>
    <span class="date">
      <%= l video.created_at, format: :short_date_time %>
    </span>
  </div>
</div>

app/views/videos/_video.html.erb
<div class="modal <%= dom_class(video) %>" id="<%= dom_id(video) %>">
  <div class="wrapper">
    <label for="modal-<%= video.id %>">
      <% if video.youtube_id? %>
        <div
          class="youtube_container"
          style="background-image: url('//img.youtube.com/vi/<%= video.youtube_id %>/mqdefault.jpg')"
          >
          <%= image_tag('play_button.png', class: 'play_button') %>
        </div>
      <% end %>
      <div class="metadata">
        <div class="short_description">
          <%= strip_tags(markdown_format(video.description)).to_s.gsub(/\s+/,' ')[0..50] %> &nbsp;
        </div>
        <%= video.dce_lti_user.lis_person_name_full %>
        <span class="date">
          <%= l video.created_at, format: :short_date_time %>
        </span>
      </div>
    </label>
    <input class="modal-state" id="modal-<%= video.id %>" type="checkbox" />
    <div class="modal-window">
      <%= render 'modal_content', video: video %>
    </div>
    <div class="controls">
      <% if video.review_required? %>
        <span class="approved badge <%= video.approved %>">
          <%= t("videos.approval_state_#{video.approved}") %>
        </span>
      <% end %>
      <% if course.user_has_role?(current_user,'instructor') || video.dce_lti_user == current_user %>
        <%= render 'dropdown', video: video %>
      <% end %>
    </div>
    <div class="clearfix"></div>
  </div>
</div>

app/views/videos/index.html.erb
<div class="full-width">
  <%= render 'filters' %>
</div>
<div id="welcome-message"><%= raw markdown_format(course.welcome_message) %></div>
<div class="full-width video-list">
  <%= render @videos %>
</div>

app/views/videos/new.html.erb
<div class="full-width">
  <div class="upload-widget">
    <% if course.review_required? %>
      <p class="instructor_review_required progress_message"><%= t('videos.review_required') %></p>
    <% end %>
    <div id="upload-description-message">
      <%= raw markdown_format(course.upload_description) %>
    </div>
    <%= simple_form_for @video do |video| %>
      <%= video.input :source, label: '', collection: Video::SOURCES, as: :radio_buttons %>
      <p id="uploading_in_progress" class="progress_message" style="display: none;">
        <%= image_tag('small_progress.gif', align: 'right') %>
        <%= t('videos.uploading_in_progress') %>
      </p>
      <div id="existing" class="source_info" style="display: none;">
        <%= video.input :existing_youtube_video %>
        <div class="hint get_help_uploading"><%= link_to(t('videos.sources.get_help_uploading'), '//support.google.com/youtube/answer/57407', target: :blank) %></div>
      </div>
      <div id="no_video" class="source_info" style="display: none;">
        <%= t('videos.sources.no_video_description') %>
      </div>
      <%= video.input :description, as: :text %>
      <%= video.input :youtube_id, as: :hidden %>
      <div id="submission_error" class="flash-error" style="display:none">
        <%= t('videos.submission_error') %>
      </div>
      <%= video.button :submit %>
    <% end %>
  </div>
  <div class="upload-player">
    <div id="preview"></div>
  </div>
</div>

app/views/videos/show.html.erb
<div class="full-width">
  <% if @my_video.persisted? %>
    <h3><%= t('videos.your_current_video') %></h3>
    <p><%= t('videos.resubmit') %></p>
    <%= render @my_video %>
  <% else %>
    <h3><%= t('videos.none_uploaded_yet') %></h3>
  <% end %>
</div>